### PR TITLE
feat(Home): social media styling

### PR DESCRIPTION
**Pull request by stanleyarmstrong**

### CODE REVIEW

**Review by selynna — CHANGES_REQUESTED** [review]
Looks good, but can you resolve the pull request? @mianuddin confirmed this works after running it on my local machine

**Comment by stanleyarmstrong** [comment]
What changes do I need to make?

**Comment by stanleyarmstrong** [comment]
@selynna

**Comment by selynna** [comment]
@stonewallstan it was padding, making sure that the strong tags were removed, but that was pretty much it. i think there's more specific style things we need to work on but dw about them for now

**Comment by mianuddin** [comment]
screen shot 2019-01-30 at 17 42 57

**Comment by mianuddin** [comment]
This is potentially unrelated, but there are button styling inconsistencies:
screen shot 2019-01-30 at 17 43 22

**Comment by stanleyarmstrong** [comment]
Oh, that's because there's no link there at the moment. I need to receive that from Hacker Experience still

**Comment by stanleyarmstrong** [comment]
But yeah I can fix that as well

**Pull request merged**
